server {
    listen 80;
    server_name thathaythach.io.vn www.thathaythach.io.vn;

    root /var/www/thathaythach;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|svg|png|jpg|jpeg|webp|ico|json|xml|txt)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }
}
